using Test

include("test_car2int.jl")
include("test_io.jl")
include("test_validate_dni.jl")
include("test_validate_isbn.jl")

# ElStruct
include("test_mcmurchie_davidson.jl")
include("test_hf_szabo.jl")

# NumQuad
include("test_gauss_legendre.jl")
include("test_clenshaw_curtis.jl")
include("test_gauss_chebyshev1st.jl")
include("test_gauss_chebyshev2nd.jl")
include("test_euler_mclaurin.jl")
include("test_trapezoidal.jl")
include("test_lebedev_laikov.jl")

# Algorithms from THE BOOK
include("test_archimedes.jl")
include("test_babylonian.jl")
include("test_eratosthenes.jl")
include("test_euclid.jl")
include("test_peasantproduct.jl")
include("test_quadratic.jl")
include("test_binarysearch.jl")
include("test_bisect.jl")
include("test_heapsort.jl")
#include("test_priorityqueue.jl")
include("test_quickselect.jl")
include("test_quicksort.jl")
include("test_adjacency.jl")
include("test_connect.jl")
include("test_dijkstra.jl")
include("test_prim.jl")
include("test_perfectpower.jl")
include("test_powermod.jl")
include("test_prime_test.jl")
include("test_cholesky.jl")
include("test_conjugategradients.jl")
include("test_gauss.jl")
include("test_gram_schmidt.jl")
#include("test_fastlog.jl")
#include("test_logistic.jl")
#include("test_newton.jl")
#include("test_secular.jl")
#include("test_karmarkar.jl")
#include("test_revisedsimplex.jl")
#include("test_cuppen.jl")
#include("test_easysvd.jl")
#include("test_householder.jl")
#include("test_jacobi.jl")
#include("test_nash.jl")
#include("test_pagerank.jl")
#include("test_rayleigh.jl")
#include("test_symtridiag.jl")
#include("test_ANOVA.jl")
#include("test_cosine_min.jl")
#include("test_dirichlet.jl")
#include("test_negbinomial.jl")
#include("test_emcluster.jl")
#include("test_kmeans.jl")
#include("test_knn.jl")
#include("test_mcda.jl")
#include("test_naiveBayes.jl")
#include("test_nmf.jl")
#include("test_convolve.jl")
#include("test_fft.jl")
#include("test_anneal.jl")
#include("test_deviate_discrete.jl")
#include("test_deviate_gamma.jl")
#include("test_deviate_normal.jl")
#include("test_deviate_poisson.jl")
#include("test_deviate_uniform.jl")
#include("test_deviate_zipf.jl")
#include("test_matrixmultiply.jl")
#include("test_mcmc_coal.jl")
#include("test_mcmc_hardcore.jl")

# Mixed language
include("test_callfortran.jl")
